app = "cc-api"
primary_region = "bog"

[build]
  dockerfile = "apps/api/Dockerfile"

[env]
  PORT = "4000"

[http_service]
  internal_port = 4000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 1
